### PR TITLE
Added / implemented callbacks

### PR DESCRIPTION
**Pull request by 6heads**
-added onCheck
-implemented onCheck, onCheckMate, onDraw

### CODE REVIEW

**Comment by 6heads** [comment]
Strings just don't fit, because it wasn't clear to me what to send on implementation (w/b or white/black, what if you use another language...). 
And because there are only two possibilities bool came quite natural.
Personally I prefer using enums when there are more than two values. What I didn't like here is that one has to define an enum for a result that comes from another library, where there is already something similar. But I could live with an enum as well ;-)

**Comment by 6heads** [comment]
Anything preventing the merge?

**Comment by deven98** [comment]
Hey @6heads, sorry for the delayed response, was busy for a few weeks. The PR looks great, will review once and merge it by today. Thanks for your contribution!

**Comment by 6heads** [comment]
(-:

Btw do you have plans for supporting minichess aka 5x6 fields and so on?

**Comment by deven98** [comment]
Merged, I'll definitely look into minichess as well.

**Comment by 6heads** [comment]
Thanks, that would be nice 🥇

**Comment by 6heads** [comment]
Any news on the minichess-thing? And could you push the new version, 0.9.5 probably, to dart packages?

**Comment by 6heads** [comment]
@deven98 Any news on the minichess-thing? And could you push the new version, 0.9.5 probably, to dart packages?

**Pull request merged**
